### ISSUE TITLE
Error in console when submitting announcement to explorer

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/krystal-bull#74]
https://oracle.suredbits.com/announcement/f6af1b70e066d1b40583e57e89e73961b56c8913595e5bb33ce687e8b9fe500b

This occurred when testing #72 (d2ef9cca) but i think it is unrelated

>2021-06-23T18:21:04UTC ERROR [ViewEventDialog$] Error retrieving announcement from explorer
java.lang.RuntimeException: Failed to parse response for listevents, err=JsError(List((,List(JsonValidationError(List(error.expected.jsobject),List())))))
	at org.bitcoins.explorer.client.SbExplorerClient.$anonfun$getAnnouncement$1(SbExplorerClient.scala:75)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by benthecarman** [comment]
Closed by #77
